{"uuid": "6c31994e-49f5-4a66-aa8e-73e786eacf34", "children": ["ae909bba-84bc-4bdf-b55e-699a914018bf"], "befores": [{"name": "refresh_page", "status": "passed", "start": 1663140781396, "stop": 1663140781396}], "afters": [{"name": "refresh_page::0", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=105.0.5195.102)\nStacktrace:\nBacktrace:\n\tOrdinal0 [0x00BCDF13+2219795]\n\tOrdinal0 [0x00B62841+1779777]\n\tOrdinal0 [0x00A7423D+803389]\n\tOrdinal0 [0x00A5C70A+706314]\n\tOrdinal0 [0x00AC1502+1119490]\n\tOrdinal0 [0x00ACE8FA+1173754]\n\tOrdinal0 [0x00ABE616+1107478]\n\tOrdinal0 [0x00A97F89+950153]\n\tOrdinal0 [0x00A98F56+954198]\n\tGetHandleVerifier [0x00EC2CB2+3040210]\n\tGetHandleVerifier [0x00EB2BB4+2974420]\n\tGetHandleVerifier [0x00C66A0A+565546]\n\tGetHandleVerifier [0x00C65680+560544]\n\tOrdinal0 [0x00B69A5C+1808988]\n\tOrdinal0 [0x00B6E3A8+1827752]\n\tOrdinal0 [0x00B6E495+1827989]\n\tOrdinal0 [0x00B780A4+1867940]\n\tBaseThreadInitThunk [0x776CFA29+25]\n\tRtlGetAppContainerNamedObjectPath [0x77CF7A9E+286]\n\tRtlGetAppContainerNamedObjectPath [0x77CF7A6E+238]\n\n", "trace": "  File \"J:\\programe\\python3\\lib\\site-packages\\allure_commons\\_allure.py\", line 200, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"J:\\programe\\python3\\lib\\site-packages\\_pytest\\fixtures.py\", line 899, in _teardown_yield_fixture\n    next(it)\n  File \"J:\\programe\\python_code\\python_code\\pytest_demo\\test_case\\demo_case\\conftest.py\", line 27, in refresh_page\n    open_url.refresh()          # yield 返回了driver，所以这里才能刷新\n  File \"J:\\programe\\python3\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 675, in refresh\n    self.execute(Command.REFRESH)\n  File \"J:\\programe\\python3\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 435, in execute\n    self.error_handler.check_response(response)\n  File \"J:\\programe\\python3\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 247, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1663140782238, "stop": 1663140782284}], "start": 1663140781396, "stop": 1663140782285}