ERROR    root:my_log.py:88 [ERROR 2024-03-05 17:26:37]error logï¼šget param fail